services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./src:/src
      - ./results:/results
    env_file:
      - .env
    command: ["run", "--summary-export=/results/summary.json", "/src/fb1.api-test.ts"]
