services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./src:/src
      - ./results:/results
    env_file:
      - .env
    command: ["run", "--summary-export=/results/summary.json", "/src/fb1.api-test.ts"]
  
  monitor-ram:
    image: oven/bun:alpine
    container_name: monitor-ram
    working_dir: /app
    volumes:
      - ./src/monitor-docker-ram.ts:/app/monitor-docker-ram.ts
      - ./results:/results
    command: ["bun", "monitor-docker-ram.ts", API_CONTAINER_NAME, TEST_RAM_INT_MS]
